[features]
seeds = false
skip-lint = false
[programs.localnet]
voting_contract = "EEp6bMYAxCQ5MpR2XCFB1ysdMtYopWqdspTYK3CxwKHw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bhimgouda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
